// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuK67ZqeeDn7U0mdobCwPNYNlqVTC5vv0',
    appId: '1:7747120549:web:49c9aae7219721f7594c4c',
    messagingSenderId: '7747120549',
    projectId: 'auth-a7281',
    authDomain: 'auth-a7281.firebaseapp.com',
    storageBucket: 'auth-a7281.appspot.com',
    measurementId: 'G-ZML6TVPMY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNsP9hGC9ovQdUHYVsibpArQNt8s_aNuU',
    appId: '1:7747120549:android:2edf365e23fad522594c4c',
    messagingSenderId: '7747120549',
    projectId: 'auth-a7281',
    storageBucket: 'auth-a7281.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk5Gtr1gasWemBCbQBIgk2tVWoWMgFxGs',
    appId: '1:7747120549:ios:b4214dfb102f3fed594c4c',
    messagingSenderId: '7747120549',
    projectId: 'auth-a7281',
    storageBucket: 'auth-a7281.appspot.com',
    iosBundleId: 'com.example.firebaseFTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk5Gtr1gasWemBCbQBIgk2tVWoWMgFxGs',
    appId: '1:7747120549:ios:25885bfdd0f86354594c4c',
    messagingSenderId: '7747120549',
    projectId: 'auth-a7281',
    storageBucket: 'auth-a7281.appspot.com',
    iosBundleId: 'com.example.firebaseFTest.RunnerTests',
  );
}
